# Generated by Django 3.1.5 on 2021-01-30 10:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210126_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('FullName', models.CharField(max_length=200)),
                ('BanglaName', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='userImages/')),
                ('designation', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=200)),
                ('otherContact', models.CharField(max_length=200)),
                ('personalDetails', ckeditor.fields.RichTextField()),
                ('ResearchArea', ckeditor.fields.RichTextField()),
                ('Research_Interest', ckeditor.fields.RichTextField()),
                ('Academic_Background', ckeditor.fields.RichTextField()),
                ('Selected_Publications', ckeditor.fields.RichTextField()),
                ('Journal_and_Conferences', ckeditor.fields.RichTextField()),
                ('Journal_Papers', ckeditor.fields.RichTextField()),
                ('Conference_Papers', ckeditor.fields.RichTextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
